language: python
os: linux
python:
    - 2.7
addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libopenmpi-dev
            - openmpi-bin
            # These don't help speed up build due to virtual-env
            #- python-h5py
            #- cython
install:
    - "pip install -r requirements.txt"
    - "python setup.py develop"
    - "pip install -r doc/requirements.txt"
script:
    - "sphinx-build -b html doc/ doc/_build/html"
    - "cd ~; nosetests gbtim_core"

